version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: school-management-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_password
      POSTGRES_DB: school_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U school_user -d school_management"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
