// Auto-generated i18n configuration
// Do not edit this file manually - it will be overwritten

import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// Import all translation files
import analytics_en from './locales/en/analytics.json';
import assessments_en from './locales/en/assessments.json';
import attendance_en from './locales/en/attendance.json';
import auth_en from './locales/en/auth.json';
import cms_en from './locales/en/cms.json';
import common_en from './locales/en/common.json';
import dashboard_en from './locales/en/dashboard.json';
import forms_en from './locales/en/forms.json';
import groups_en from './locales/en/groups.json';
import navigation_en from './locales/en/navigation.json';
import settings_en from './locales/en/settings.json';
import students_en from './locales/en/students.json';
import tasks_en from './locales/en/tasks.json';
import analytics_fr from './locales/fr/analytics.json';
import assessments_fr from './locales/fr/assessments.json';
import attendance_fr from './locales/fr/attendance.json';
import auth_fr from './locales/fr/auth.json';
import cms_fr from './locales/fr/cms.json';
import common_fr from './locales/fr/common.json';
import dashboard_fr from './locales/fr/dashboard.json';
import forms_fr from './locales/fr/forms.json';
import groups_fr from './locales/fr/groups.json';
import navigation_fr from './locales/fr/navigation.json';
import settings_fr from './locales/fr/settings.json';
import students_fr from './locales/fr/students.json';
import tasks_fr from './locales/fr/tasks.json';
import analytics_de from './locales/de/analytics.json';
import assessments_de from './locales/de/assessments.json';
import attendance_de from './locales/de/attendance.json';
import auth_de from './locales/de/auth.json';
import cms_de from './locales/de/cms.json';
import common_de from './locales/de/common.json';
import dashboard_de from './locales/de/dashboard.json';
import forms_de from './locales/de/forms.json';
import groups_de from './locales/de/groups.json';
import navigation_de from './locales/de/navigation.json';
import settings_de from './locales/de/settings.json';
import students_de from './locales/de/students.json';
import tasks_de from './locales/de/tasks.json';
import analytics_it from './locales/it/analytics.json';
import assessments_it from './locales/it/assessments.json';
import attendance_it from './locales/it/attendance.json';
import auth_it from './locales/it/auth.json';
import cms_it from './locales/it/cms.json';
import common_it from './locales/it/common.json';
import dashboard_it from './locales/it/dashboard.json';
import forms_it from './locales/it/forms.json';
import groups_it from './locales/it/groups.json';
import navigation_it from './locales/it/navigation.json';
import settings_it from './locales/it/settings.json';
import students_it from './locales/it/students.json';
import tasks_it from './locales/it/tasks.json';
import analytics_nl from './locales/nl/analytics.json';
import assessments_nl from './locales/nl/assessments.json';
import attendance_nl from './locales/nl/attendance.json';
import auth_nl from './locales/nl/auth.json';
import cms_nl from './locales/nl/cms.json';
import common_nl from './locales/nl/common.json';
import dashboard_nl from './locales/nl/dashboard.json';
import forms_nl from './locales/nl/forms.json';
import groups_nl from './locales/nl/groups.json';
import navigation_nl from './locales/nl/navigation.json';
import settings_nl from './locales/nl/settings.json';
import students_nl from './locales/nl/students.json';
import tasks_nl from './locales/nl/tasks.json';
import analytics_es from './locales/es/analytics.json';
import assessments_es from './locales/es/assessments.json';
import attendance_es from './locales/es/attendance.json';
import auth_es from './locales/es/auth.json';
import cms_es from './locales/es/cms.json';
import common_es from './locales/es/common.json';
import dashboard_es from './locales/es/dashboard.json';
import forms_es from './locales/es/forms.json';
import groups_es from './locales/es/groups.json';
import navigation_es from './locales/es/navigation.json';
import settings_es from './locales/es/settings.json';
import students_es from './locales/es/students.json';
import tasks_es from './locales/es/tasks.json';

const resources = {
  en: {
    analytics: analytics_en,
    assessments: assessments_en,
    attendance: attendance_en,
    auth: auth_en,
    cms: cms_en,
    common: common_en,
    dashboard: dashboard_en,
    forms: forms_en,
    groups: groups_en,
    navigation: navigation_en,
    settings: settings_en,
    students: students_en,
    tasks: tasks_en,
  },
  fr: {
    analytics: analytics_fr,
    assessments: assessments_fr,
    attendance: attendance_fr,
    auth: auth_fr,
    cms: cms_fr,
    common: common_fr,
    dashboard: dashboard_fr,
    forms: forms_fr,
    groups: groups_fr,
    navigation: navigation_fr,
    settings: settings_fr,
    students: students_fr,
    tasks: tasks_fr,
  },
  de: {
    analytics: analytics_de,
    assessments: assessments_de,
    attendance: attendance_de,
    auth: auth_de,
    cms: cms_de,
    common: common_de,
    dashboard: dashboard_de,
    forms: forms_de,
    groups: groups_de,
    navigation: navigation_de,
    settings: settings_de,
    students: students_de,
    tasks: tasks_de,
  },
  it: {
    analytics: analytics_it,
    assessments: assessments_it,
    attendance: attendance_it,
    auth: auth_it,
    cms: cms_it,
    common: common_it,
    dashboard: dashboard_it,
    forms: forms_it,
    groups: groups_it,
    navigation: navigation_it,
    settings: settings_it,
    students: students_it,
    tasks: tasks_it,
  },
  nl: {
    analytics: analytics_nl,
    assessments: assessments_nl,
    attendance: attendance_nl,
    auth: auth_nl,
    cms: cms_nl,
    common: common_nl,
    dashboard: dashboard_nl,
    forms: forms_nl,
    groups: groups_nl,
    navigation: navigation_nl,
    settings: settings_nl,
    students: students_nl,
    tasks: tasks_nl,
  },
  es: {
    analytics: analytics_es,
    assessments: assessments_es,
    attendance: attendance_es,
    auth: auth_es,
    cms: cms_es,
    common: common_es,
    dashboard: dashboard_es,
    forms: forms_es,
    groups: groups_es,
    navigation: navigation_es,
    settings: settings_es,
    students: students_es,
    tasks: tasks_es,
  },
} as const;

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    debug: process.env.NODE_ENV === 'development',
    
    interpolation: {
      escapeValue: false,
    },
    
    detection: {
      order: ['localStorage', 'navigator', 'htmlTag'],
      caches: ['localStorage'],
    },
    
    defaultNS: 'common',
    ns: ['analytics', 'assessments', 'attendance', 'auth', 'cms', 'common', 'dashboard', 'forms', 'groups', 'navigation', 'settings', 'students', 'tasks'],
  });

export default i18n;
export { resources };
