// Auto-generated useTranslation hook with type safety
// Do not edit this file manually - it will be overwritten

import { useTranslation as useI18nTranslation } from 'react-i18next';
import type { TranslationKey } from './types';

export function useTranslation<T extends TranslationKey = 'common'>(ns?: T) {
  return useI18nTranslation(ns);
}

export function useT() {
  const { t } = useI18nTranslation();
  return t;
}
