// Auto-generated i18n exports
// Do not edit this file manually - it will be overwritten

export { default as i18n } from './config';
export { useTranslation, useT } from './hook';
export type { TranslationKey, CategoryKey } from './types';
