// Auto-generated TypeScript definitions for i18n
// Do not edit this file manually - it will be overwritten

import 'react-i18next';

interface AnalyticsTranslations {
  average_score_trend: string;
  avg_class_size: string;
  avg_submission_rate: string;
  chart_labels: {
    absent: string;
    late: string;
    present: string;
  };
  charts: {
    attendance_trend: string;
    grade_distribution: string;
    performance_trend: string;
    task_completion_rate: string;
    top_performers: string;
  };
  detailed_statistics: string;
  error_loading: string;
  loading: string;
  metrics: {
    active_students: string;
    attendance_rate: string;
    average_score: string;
    based_on_graded: string;
    currently_enrolled: string;
    graded_assessments: string;
    last_7_days: string;
    tasks_completed: string;
  };
  no_data_available: string;
  pass_rate: string;
  performance_insights: string;
  student_performance: string;
  subtitle: string;
  task_completion: string;
  title: string;
  total_assignments: string;
  weekly_attendance: string;
}

interface AssessmentsTranslations {
  actions: {
    grade: string;
    view: string;
  };
  filters: {
    all: string;
    not_submitted: string;
    to_grade: string;
  };
  loading: string;
  no_assessments: string;
  no_submission: string;
  stats: {
    graded: string;
    late: string;
    missing: string;
    pending: string;
    total: string;
  };
  subtitle: string;
  table: {
    all_assessments: string;
    grade: string;
    score: string;
    student: string;
    submitted: string;
    task: string;
    type: string;
  };
  title: string;
}

interface AttendanceTranslations {
  actions: {
    mark_all_absent: string;
    mark_all_present: string;
  };
  export_report: string;
  form: {
    date_label: string;
    group_label: string;
    select_group: string;
  };
  loading_students: string;
  messages: {
    attendance_failed: string;
    attendance_marked: string;
    bulk_marked: string;
  };
  no_students: string;
  select_group_message: string;
  stats: {
    absent: string;
    excused: string;
    late: string;
    present: string;
    total: string;
  };
  students_title: string;
  subtitle: string;
  title: string;
}

interface AuthTranslations {
  login: {
    email: string;
    email_placeholder: string;
    password: string;
    signing_in: string;
    submit: string;
    subtitle: string;
    title: string;
  };
  login_error: string;
  login_successful: string;
  logout: string;
  welcome_back: string;
}

interface CmsTranslations {
  analytics: {
    avg_session: string;
    daily_active_users: string;
    page_views: string;
    subtitle: string;
    system_load: string;
    title: string;
  };
  settings: {
    database_settings: string;
    email_settings: string;
    general_settings: string;
    security_settings: string;
    subtitle: string;
    title: string;
  };
  system_settings: string;
  title: string;
  translations: string;
  user_management: string;
}

interface CommonTranslations {
  account_info: string;
  account_type: string;
  back: string;
  cancel: string;
  change_password: string;
  delete: string;
  edit: string;
  error: string;
  export: string;
  filter: string;
  import: string;
  last_login: string;
  loading: string;
  logout: string;
  member_since: string;
  next: string;
  notification_preferences_updated: string;
  password_changed: string;
  passwords_no_match: string;
  profile_updated: string;
  refresh: string;
  save: string;
  save_changes: string;
  search: string;
  success: string;
  update_profile: string;
  view: string;
}

interface DashboardTranslations {
  attendance: {
    absent: string;
    excused: string;
    late: string;
    present: string;
    title: string;
  };
  detail: {
    active_tasks: string;
    add_first_student: string;
    create_first_task: string;
    loading: string;
    no_students: string;
    no_tasks: string;
    recent_tasks: string;
    students: string;
    total_students: string;
    tutors: string;
  };
  due_in_days: string;
  due_next_week: string;
  due_tomorrow: string;
  late_submission: string;
  loading: string;
  overview: string;
  recent_activity: string;
  recent_submissions: string;
  recent_tasks: string;
  statistics: string;
  stats: {
    active_class_groups: string;
    active_students_enrolled: string;
    active_tasks: string;
    awaiting_grading: string;
    pending_assessments: string;
    published_assignments: string;
    total_groups: string;
    total_students: string;
  };
  submitted: string;
  title: string;
  welcome: string;
}

interface FormsTranslations {
  invalid_email: string;
  required_field: string;
}

interface GroupsTranslations {
  actions: {
    delete_group: string;
    edit_group: string;
    view_details: string;
  };
  add_group: string;
  create_group: string;
  detail: {
    active_tasks: string;
    add_first_student: string;
    add_student: string;
    cancel: string;
    create_first_task: string;
    create_task: string;
    edit_dialog: {
      academic_year: string;
      grade: string;
      group_code: string;
      group_name: string;
      title: string;
    };
    edit_group: string;
    loading: string;
    move_student: string;
    move_student_dialog: {
      choose_student: string;
      choose_target_group: string;
      move_button: string;
      select_student: string;
      target_group: string;
      title: string;
    };
    no_students: string;
    no_tasks: string;
    recent_tasks: string;
    remove_student_dialog: {
      description: string;
      remove_button: string;
      title: string;
    };
    save_changes: string;
    stats: {
      assessments: string;
      attendance: string;
      submissions: string;
    };
    students: string;
    task_info: {
      due_date: string;
    };
    total_students: string;
    tutors: string;
  };
  form: {
    academic_year_label: string;
    code_label: string;
    grade_label: string;
    name_label: string;
  };
  loading: string;
  no_groups: string;
  stats: {
    academic_year: string;
    active_groups: string;
    active_tasks_label: string;
    grade: string;
    students: string;
    total_groups: string;
    total_students_in_groups: string;
    tutors_label: string;
  };
  subtitle: string;
  title: string;
}

interface NavigationTranslations {
  analytics: string;
  assessments: string;
  attendance: string;
  auth: {
    logout: string;
  };
  dashboard: string;
  groups: string;
  settings: string;
  students: string;
  tasks: string;
}

interface SettingsTranslations {
  account: {
    ensure_secure: string;
  };
  language_preferences: string;
  notification_settings: string;
  notifications: {
    attendance_alerts: string;
    description: string;
    email_notifications: string;
    grade_updates: string;
    task_reminders: string;
    title: string;
    weekly_reports: string;
  };
  profile: {
    description: string;
    email: string;
    full_name: string;
    phone: string;
    title: string;
  };
  profile_settings: string;
  security: {
    change_password: string;
    confirm_password: string;
    current_password: string;
    new_password: string;
    title: string;
  };
  subtitle: string;
  system: {
    title: string;
  };
  tabs: {
    notifications: string;
    profile: string;
    security: string;
    system: string;
  };
  title: string;
}

interface StudentsTranslations {
  actions: {
    delete_student: string;
    edit_student: string;
    view_details: string;
  };
  add_new_student: string;
  add_student: string;
  delete_confirmation: string;
  detail: {
    academic_information: string;
    all_years: string;
    assignment_history: string;
    assignment_number: string;
    assignments_completed_on_time: string;
    average_score: string;
    back_to_students: string;
    based_on_assessments: string;
    born: string;
    charts: string;
    completed: string;
    completion_rate: string;
    contact: string;
    contact_information: string;
    current_group: string;
    details: string;
    due: string;
    enrolled: string;
    enrolled_label: string;
    failed_to_load: string;
    grade: string;
    group: string;
    latest: string;
    loading: string;
    no_assignments_found: string;
    no_assignments_period: string;
    no_code: string;
    no_due_date: string;
    no_group: string;
    not_graded: string;
    notes: string;
    parent_contacts: string;
    performance_overview: string;
    primary: string;
    score_percent: string;
    score_trend: string;
    score_trends_analytics: string;
    select_year: string;
    status: string;
    student_details: string;
    student_id: string;
    student_information: string;
    submitted: string;
    task_types_distribution: string;
    total_assignments: string;
  };
  edit_student: string;
  form: {
    create_student: string;
    email_label: string;
    group_label: string;
    loading_groups: string;
    name_label: string;
    notes_label: string;
    select_group: string;
    update_student: string;
  };
  no_students: string;
  search_placeholder: string;
  stats: {
    active: string;
    groups: string;
    inactive: string;
    total_students: string;
  };
  subtitle: string;
  table: {
    actions: string;
    all_students: string;
    email: string;
    enrolled: string;
    group: string;
    name: string;
    status: string;
    student_id: string;
    unassigned: string;
  };
  title: string;
}

interface TasksTranslations {
  actions: {
    delete_task: string;
    edit_task: string;
    view_details: string;
  };
  assigned_groups: string;
  back_to_tasks: string;
  category: string;
  create_task: string;
  created: string;
  delete_confirmation: string;
  description: string;
  details: string;
  draft: string;
  due: string;
  edit_task: string;
  export_results: string;
  failed_to_load_task: string;
  form: {
    category_label: string;
    create_new_task: string;
    description_label: string;
    due_date_label: string;
    groups_label: string;
    instructions_label: string;
    points_label: string;
    publish_immediately: string;
    title_label: string;
    type_label: string;
  };
  instructions: string;
  last_updated: string;
  loading: string;
  loading_task_details: string;
  no_submissions_for_task: string;
  no_submissions_yet: string;
  no_tasks: string;
  not_graded: string;
  points: string;
  published: string;
  stats: {
    all_tasks: string;
    average_score: string;
    awaiting_grading: string;
    based_on_grades: string;
    drafts: string;
    due_this_week: string;
    graded: string;
    missing_submissions: string;
    not_submitted: string;
    out_of_students: string;
    pending: string;
    percent_of_submissions: string;
    published: string;
    total_submissions: string;
    total_tasks: string;
  };
  status: {
    draft: string;
    graded: string;
    late: string;
    not_submitted: string;
    submitted: string;
  };
  student_submissions: string;
  submissions_preview: string;
  submitted: string;
  subtitle: string;
  task_details: string;
  task_information: string;
  title: string;
  type: string;
  types: {
    assignment: string;
    exam: string;
    homework: string;
    project: string;
    quiz: string;
  };
}

interface Resources {
  analytics: AnalyticsTranslations;
  assessments: AssessmentsTranslations;
  attendance: AttendanceTranslations;
  auth: AuthTranslations;
  cms: CmsTranslations;
  common: CommonTranslations;
  dashboard: DashboardTranslations;
  forms: FormsTranslations;
  groups: GroupsTranslations;
  navigation: NavigationTranslations;
  settings: SettingsTranslations;
  students: StudentsTranslations;
  tasks: TasksTranslations;
}

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: Resources;
  }
}

export type TranslationKey = keyof Resources;
export type CategoryKey<T extends TranslationKey> = keyof Resources[T];
