// Auto-generated TypeScript definitions for i18n
// Do not edit this file manually - it will be overwritten

import 'react-i18next';

interface AnalyticsTranslations {
  loading: string;
  student_performance: string;
  subtitle: string;
  task_completion: string;
  title: string;
}

interface AssessmentsTranslations {
  actions: {
    grade: string;
    view: string;
  };
  filters: {
    all: string;
    not_submitted: string;
    to_grade: string;
  };
  loading: string;
  no_assessments: string;
  no_submission: string;
  stats: {
    graded: string;
    late: string;
    missing: string;
    pending: string;
    total: string;
  };
  subtitle: string;
  table: {
    all_assessments: string;
    grade: string;
    score: string;
    student: string;
    submitted: string;
    task: string;
    type: string;
  };
  title: string;
}

interface AttendanceTranslations {
  actions: {
    mark_all_absent: string;
    mark_all_present: string;
  };
  export_report: string;
  form: {
    date_label: string;
    group_label: string;
    select_group: string;
  };
  loading_students: string;
  messages: {
    attendance_failed: string;
    attendance_marked: string;
    bulk_marked: string;
  };
  no_students: string;
  select_group_message: string;
  stats: {
    absent: string;
    excused: string;
    late: string;
    present: string;
    total: string;
  };
  students_title: string;
  subtitle: string;
  title: string;
}

interface AuthTranslations {
  login: {
    email: string;
    email_placeholder: string;
    password: string;
    signing_in: string;
    submit: string;
    subtitle: string;
    title: string;
  };
  login_error: string;
  login_successful: string;
  logout: string;
  welcome_back: string;
}

interface CmsTranslations {
  analytics: {
    avg_session: string;
    daily_active_users: string;
    page_views: string;
    subtitle: string;
    system_load: string;
    title: string;
  };
  settings: {
    database_settings: string;
    email_settings: string;
    general_settings: string;
    security_settings: string;
    subtitle: string;
    title: string;
  };
  system_settings: string;
  title: string;
  translations: string;
  user_management: string;
}

interface CommonTranslations {
  back: string;
  cancel: string;
  delete: string;
  edit: string;
  error: string;
  export: string;
  filter: string;
  import: string;
  loading: string;
  logout: string;
  next: string;
  refresh: string;
  save: string;
  search: string;
  success: string;
  view: string;
}

interface DashboardTranslations {
  attendance: {
    absent: string;
    excused: string;
    late: string;
    present: string;
    title: string;
  };
  due_in_days: string;
  due_next_week: string;
  due_tomorrow: string;
  late_submission: string;
  loading: string;
  overview: string;
  recent_activity: string;
  recent_submissions: string;
  recent_tasks: string;
  statistics: string;
  stats: {
    active_class_groups: string;
    active_students_enrolled: string;
    active_tasks: string;
    awaiting_grading: string;
    pending_assessments: string;
    published_assignments: string;
    total_groups: string;
    total_students: string;
  };
  submitted: string;
  title: string;
  welcome: string;
}

interface FormsTranslations {
  invalid_email: string;
  required_field: string;
}

interface GroupsTranslations {
  add_group: string;
  form: {
    academic_year_label: string;
    code_label: string;
    grade_label: string;
    name_label: string;
  };
  loading: string;
  no_groups: string;
  stats: {
    active_groups: string;
    total_groups: string;
    total_students_in_groups: string;
  };
  subtitle: string;
  title: string;
}

interface NavigationTranslations {
  analytics: string;
  assessments: string;
  attendance: string;
  dashboard: string;
  groups: string;
  settings: string;
  students: string;
  tasks: string;
}

interface SettingsTranslations {
  language_preferences: string;
  notification_settings: string;
  profile_settings: string;
  subtitle: string;
  title: string;
}

interface StudentsTranslations {
  add_new_student: string;
  add_student: string;
  delete_confirmation: string;
  edit_student: string;
  form: {
    create_student: string;
    email_label: string;
    group_label: string;
    loading_groups: string;
    name_label: string;
    notes_label: string;
    select_group: string;
    update_student: string;
  };
  no_students: string;
  search_placeholder: string;
  stats: {
    active: string;
    groups: string;
    inactive: string;
    total_students: string;
  };
  subtitle: string;
  table: {
    actions: string;
    email: string;
    enrolled: string;
    group: string;
    name: string;
    status: string;
    student_id: string;
    unassigned: string;
  };
  title: string;
}

interface TasksTranslations {
  create_task: string;
  delete_confirmation: string;
  form: {
    category_label: string;
    create_new_task: string;
    description_label: string;
    due_date_label: string;
    groups_label: string;
    instructions_label: string;
    points_label: string;
    publish_immediately: string;
    title_label: string;
    type_label: string;
  };
  loading: string;
  no_tasks: string;
  stats: {
    drafts: string;
    due_this_week: string;
    published: string;
    total_tasks: string;
  };
  subtitle: string;
  title: string;
  types: {
    assignment: string;
    exam: string;
    homework: string;
    project: string;
    quiz: string;
  };
}

interface Resources {
  analytics: AnalyticsTranslations;
  assessments: AssessmentsTranslations;
  attendance: AttendanceTranslations;
  auth: AuthTranslations;
  cms: CmsTranslations;
  common: CommonTranslations;
  dashboard: DashboardTranslations;
  forms: FormsTranslations;
  groups: GroupsTranslations;
  navigation: NavigationTranslations;
  settings: SettingsTranslations;
  students: StudentsTranslations;
  tasks: TasksTranslations;
}

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: Resources;
  }
}

export type TranslationKey = keyof Resources;
export type CategoryKey<T extends TranslationKey> = keyof Resources[T];
